### ISSUE TITLE
TaxonInfoBase.expandName NPE in logs

### ISSUE THREAD

**Issue by mdoering** [mdoering/wikipedia-dwca#15]
found in logs

DEBUG Processing #1180 http://en.wikipedia.org/wiki/Areca: Areca
java.lang.NullPointerException
        at java.util.regex.Matcher.getTextLength(Matcher.java:1234)
        at java.util.regex.Matcher.reset(Matcher.java:308)
        at java.util.regex.Matcher.<init>(Matcher.java:228)
        at java.util.regex.Pattern.matcher(Pattern.java:1088)
        at org.tdwg.dwca.wikipedia.taxonbox.TaxonInfoBase.expandName(TaxonInfoBase.java:178)
        at org.tdwg.dwca.wikipedia.taxonbox.TaxonInfoBase.postprocess(TaxonInfoBase.java:134)
        at org.tdwg.dwca.wikipedia.taxonbox.TaxonInfoEN.postprocess(TaxonInfoEN.java:31)
        at org.tdwg.dwca.wikipedia.TaxonboxHandler.processTaxonPage(TaxonboxHandler.java:158)
        at org.tdwg.dwca.wikipedia.TaxonboxHandler.process(TaxonboxHandler.java:97)
        at info.bliki.wiki.dump.WikiXMLParser.endElement(WikiXMLParser.java:185)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:609)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1782)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2973)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
        at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:117)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
        at info.bliki.wiki.dump.WikiXMLParser.parse(WikiXMLParser.java:221)
        at org.tdwg.dwca.wikipedia.ChecklistBuilder.parse(ChecklistBuilder.java:90)
        at org.tdwg.dwca.wikipedia.ChecklistBuilder.main(ChecklistBuilder.java:164)
DEBUG Processing #1181 http://en.wikipedia.org/wiki/Sand_dollar: Clypeasteroida

**Comment by mdoering** [comment]
Also in:

DEBUG Processing #5651 http://en.wikipedia.org/wiki/Amelanchier_alnifolia: Amelanchier alnifolia
java.lang.NullPointerException
        at java.util.regex.Matcher.getTextLength(Matcher.java:1234)
        at java.util.regex.Matcher.reset(Matcher.java:308)
        at java.util.regex.Matcher.<init>(Matcher.java:228)
        at java.util.regex.Pattern.matcher(Pattern.java:1088)
        at org.tdwg.dwca.wikipedia.taxonbox.TaxonInfoBase.expandName(TaxonInfoBase.java:178)
        at org.tdwg.dwca.wikipedia.taxonbox.TaxonInfoBase.postprocess(TaxonInfoBase.java:134)
        at org.tdwg.dwca.wikipedia.taxonbox.TaxonInfoEN.postprocess(TaxonInfoEN.java:31)
        at org.tdwg.dwca.wikipedia.TaxonboxHandler.processTaxonPage(TaxonboxHandler.java:158)
        at org.tdwg.dwca.wikipedia.TaxonboxHandler.process(TaxonboxHandler.java:97)
        at info.bliki.wiki.dump.WikiXMLParser.endElement(WikiXMLParser.java:185)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:609)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1782)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2973)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
        at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:117)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
        at info.bliki.wiki.dump.WikiXMLParser.parse(WikiXMLParser.java:221)
        at org.tdwg.dwca.wikipedia.ChecklistBuilder.parse(ChecklistBuilder.java:90)
        at org.tdwg.dwca.wikipedia.ChecklistBuilder.main(ChecklistBuilder.java:164)
DEBUG Processing #5652 http://en.wikipedia.org/wiki/Campanula: Campanula
